In [1]:
import numpy as np
data=np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
result=train_test_split(dataset)
result

[array([1, 4, 8, 2, 9, 0, 3]), array([5, 6, 7])]

In [4]:
import numpy as np
from sklearn.model_selection import train_test_split
a=np.arange(10)
result=train_test_split(a)
result[0]


array([0, 8, 3, 1, 9, 4, 6])

In [5]:
result[1]

array([7, 2, 5])

In [6]:
import numpy as np
from sklearn.model_selection import train_test_split
a=np.arange(10)
X_train,X_test=train_test_split(a)
X_train
X_test

array([7, 4, 9])

In [7]:
import numpy as np
from sklearn.model_selection import train_test_split
a=np.arange(10)
X_train,X_test=train_test_split(a,test_size=4)
X_train

array([7, 1, 2, 5, 6, 0])

In [8]:
X_test

array([9, 8, 4, 3])

In [9]:
import numpy as np
from sklearn.model_selection import train_test_split
a=np.arange(20)
X_train,X_tail=train_test_split(a,test_size=0.4)
X_train

array([15, 11, 18,  6,  8,  1, 14,  5,  2, 12, 17,  4])

In [10]:
X_test

array([9, 8, 4, 3])

In [11]:
import numpy as np
from sklearn.model_selection import train_test_split
a=np.arange(20)
X_train,X_test=train_test_split(a,test_size=0.35)
X_train

array([15, 10,  8, 16,  3, 13,  7,  9, 12,  5, 11,  0,  6])

In [12]:
X_test

array([ 2,  1, 18, 17, 19, 14,  4])

In [13]:
import numpy as np
a=np.arange(20).reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [14]:
a=np.arange(20).reshape(2,10).T
a

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

In [15]:
y=np.arange(10)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
import numpy as np
from sklearn.model_selection import train_test_split
a=np.arange(20)
result=train_test_split(a)
result

[array([13, 14,  3, 17,  5, 11,  6,  9, 10, 12,  8, 18, 15, 16,  7]),
 array([ 4, 19,  1,  2,  0])]

In [17]:
import numpy as np
from sklearn.model_selection import train_test_split
a=np.arange(20)
X_train,X_test=train_test_split(a,test_size=0.4)
X_train

array([11, 16, 10, 12,  8,  5,  1, 14,  3,  6, 17,  9])

In [18]:
X_test

array([13, 18,  2,  0,  4, 19,  7, 15])

In [19]:
import numpy as np
a=np.arange(20).reshape(10,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [20]:
import numpy as np
from sklearn.model_selection import train_test_split
a=np.arange(20)
result=train_test_split(a,test_size=0.3)
result

[array([ 3, 10,  8, 16, 11,  6, 13,  5, 19, 18, 12,  1,  0, 17]),
 array([ 2, 14,  9,  7,  4, 15])]

In [21]:
import numpy as np
from sklearn.model_selection import train_test_split
a=np.arange(10)
X_train,X_test=train_test_split(a,test_size=4)
X_train

array([8, 3, 5, 9, 1, 2])

In [22]:
X_test

array([7, 4, 6, 0])

In [23]:
import numpy as np
a=np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [24]:
a=np.arange(20).reshape(5,4).T
a

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [25]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
a={
    "names":["rajesh","maddi","today","tomorrow"],
     "values":["ok","hello","world","error"]
}
df=pd.DataFrame(a)
obj=LabelEncoder()
df["names_n"]=obj.fit_transform(df["names"])
df["values_n"]=obj.fit_transform(df["values"])
df

names values  names_n  values_n
0    rajesh     ok        1         2
1     maddi  hello        0         1
2     today  world        2         3
3  tomorrow  error        3         0

In [26]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
a={
    "x":[10,20,30,40,50],
     "y":[100,200,300,400,500]
}
df=pd.DataFrame(a)
obj=MinMaxScaler(feature_range=(0,1))
df[["x","y"]]=obj.fit_transform(df[["x","y"]])
df

x     y
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00

In [27]:
import pandas as pd
import numpy as np
a={
    "salary":[234,675,898,999],
     "values":[2,3,4,200],
      "ages":[234,789,899,678]
}
df=pd.DataFrame(a)
cond1=df["values"]<8
df[cond1]
df["outliers"]=np.where(cond1,True,False)
df

salary  values  ages  outliers
0     234       2   234      True
1     675       3   789      True
2     898       4   899      True
3     999     200   678     False

In [28]:
import pandas as pd
from sklearn.impute import SimpleImputer
students = [
              [85, 'M', 'verygood'],
              [95, 'F', 'excellent'],
              [60, np.nan, 'good'],
              [np.nan, 'M', 'average'],
               [70, 'M', 'good'],
              [np.nan, np.nan, 'verygood'],
              [60, 'F', 'verygood'],
              [98, 'M', 'excellent']]
cols=["marks","gender","result"]
df=pd.DataFrame(students,columns=cols)
obj=SimpleImputer(strategy="most_frequent")
x=df[["marks"]].values
df[["marks"]]=obj.fit_transform(x)
df

marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0    NaN       good
3   60.0      M    average
4   70.0      M       good
5   60.0    NaN   verygood
6   60.0      F   verygood
7   98.0      M  excellent

In [29]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
a=asarray([["rajesj"],["maddi"],["today"],["tomorrow"],["hyderbad"]])
obj=OrdinalEncoder()
result=obj.fit_transform(a)
result

array([[2.],
       [1.],
       [3.],
       [4.],
       [0.]])

In [30]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder
a=np.array([["rajesh"],["maddi"],["today"],["tomorrow"]])
obj=OneHotEncoder(drop="first",sparse_output=False)
result=obj.fit_transform(a)
result

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
import numpy as np
from sklearn.model_selection import train_test_split
a=np.arange(10)
result=train_test_split(a)
result[0]


array([9, 1, 0, 7, 6, 8, 5])

In [32]:
result[1]

array([2, 3, 4])

In [33]:
import numpy as np
from sklearn.model_selection import train_test_split
a=np.arange(20)
X_train,X_test=train_test_split(a,test_size=0.5)
X_train

array([ 7,  4, 17, 16,  3,  5, 15, 12, 10,  9])

In [34]:
X_test

array([ 1, 18, 19,  6, 13,  8, 14, 11,  0,  2])

In [35]:
import numpy as np
from sklearn.model_selection import train_test_split
a=np.arange(10)
result=train_test_split(a)
result

[array([4, 7, 0, 5, 1, 2, 6]), array([9, 8, 3])]

In [36]:
import numpy as np
from sklearn.model_selection import train_test_split
a=np.arange(20)
X_train,X_test=train_test_split(a,test_size=0.4)
X_train

array([ 6, 13, 17,  7, 11, 10,  8, 18,  9, 16,  1, 14])

In [37]:
X_test

array([ 2, 19,  3,  5, 12,  4, 15,  0])

In [38]:
import numpy as np
from sklearn.model_selection import train_test_split
a=np.arange(10).reshape(5,2)
result=train_test_split(a)
result

[array([[2, 3],
        [0, 1],
        [6, 7]]),
 array([[8, 9],
        [4, 5]])]

In [39]:
import numpy as np
a=np.arange(20).reshape(20,1).T
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]


In [40]:
y=np.arange(10)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [41]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
a={
    "names":["rajesh","maddi","today","tomorrow"],
     "values":["ok","hyder","vijat","rice"]
}
df=pd.DataFrame(a)
obj=LabelEncoder()
df["names_n"]=obj.fit_transform(df["names"])
df["values_n"]=obj.fit_transform(df["values"])
df

names values  names_n  values_n
0    rajesh     ok        1         1
1     maddi  hyder        0         0
2     today  vijat        2         3
3  tomorrow   rice        3         2

In [42]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
a={
    "x":[10,20,30,40,50,60],
     "y":[100,200,300,400,500,600]
}
df=pd.DataFrame(a)
obj=MinMaxScaler(feature_range=(0,1))
df[["x","y"]]=obj.fit_transform(df[["x","y"]])
df

x    y
0  0.0  0.0
1  0.2  0.2
2  0.4  0.4
3  0.6  0.6
4  0.8  0.8
5  1.0  1.0

In [43]:
import numpy as np
import pandas as pd
a={
    "values":[234,567,789,999],
     "size":[2,3,4,200],
      "area":[234,456,678,999]
}
df=pd.DataFrame(a)
cond1=df["size"]<6
df[cond1]

values  size  area
0     234     2   234
1     567     3   456
2     789     4   678

In [44]:
df["outliers"]=np.where(cond1,True,False)
df

values  size  area  outliers
0     234     2   234      True
1     567     3   456      True
2     789     4   678      True
3     999   200   999     False

In [45]:
import pandas as pd
from sklearn.impute import SimpleImputer
students = [
              [85, 'M', 'verygood'],
              [95, 'F', 'excellent'],
              [60, np.nan, 'good'],
              [np.nan, 'M', 'average'],
               [70, 'M', 'good'],
              [np.nan, np.nan, 'verygood'],
              [60, 'F', 'verygood'],
              [98, 'M', 'excellent']]
cols=["marks","gender","result"]
df=pd.DataFrame(students,columns=cols)
obj=SimpleImputer(strategy="mean")
x=df[["marks"]].values
df[["marks"]]=obj.fit_transform(x)
df

marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
2   60.0    NaN       good
3   78.0      M    average
4   70.0      M       good
5   78.0    NaN   verygood
6   60.0      F   verygood
7   98.0      M  excellent

In [46]:
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
a=asarray([["rajesh"],["maddi"],["today"],["tomorrow"]])
obj=OrdinalEncoder()
result=obj.fit_transform(a)
result

array([[1.],
       [0.],
       [2.],
       [3.]])

In [47]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
a=asarray([["rajesh"],["maddi"],["today"],["tomorrow"]])
obj=OneHotEncoder(drop="first",sparse_output=False)
result=obj.fit_transform(a)
result

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
from sklearn.model_selection import train_test_split
import numpy as np
a=np.arange(10)
X_train,X_test=train_test_split(a,test_size=0.3)
X_train

array([3, 0, 5, 8, 6, 7, 2])

In [49]:
X_test

array([9, 1, 4])

In [50]:
import numpy as np
a=np.arange(20).reshape(5,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [51]:
import pandas as pd
df=pd.read_csv("fruits1.csv")
df

Order Id  Apples  Orange  Banana
0       16723     9.0     NaN     6.0
1       16724    12.0    12.0     6.0
2       16725     9.0     NaN     NaN
3       16726    12.0     NaN    24.0
4       16727    30.0     8.0    10.0
..        ...     ...     ...     ...
145     16868    24.0    12.0     6.0
146     16869     8.0     8.0    12.0
147     16870     5.0    30.0    30.0
148     16871    24.0     NaN    10.0
149     16872     5.0    30.0    10.0

[150 rows x 4 columns]

In [52]:
df.isna().sum()

Order Id     0
Apples      16
Orange      16
Banana      21
dtype: int64

In [53]:
df.dropna(inplace=True)

In [54]:
df.isna().sum()

Order Id    0
Apples      0
Orange      0
Banana      0
dtype: int64

In [55]:
df

Order Id  Apples  Orange  Banana
1       16724    12.0    12.0     6.0
4       16727    30.0     8.0    10.0
5       16728     6.0     6.0    12.0
6       16729    12.0    24.0     9.0
7       16730    24.0     6.0     8.0
..        ...     ...     ...     ...
143     16866    12.0    10.0    10.0
145     16868    24.0    12.0     6.0
146     16869     8.0     8.0    12.0
147     16870     5.0    30.0    30.0
149     16872     5.0    30.0    10.0

[105 rows x 4 columns]

In [56]:
import pandas as pd
df=pd.read_csv("fruits1.csv")
df

Order Id  Apples  Orange  Banana
0       16723     9.0     NaN     6.0
1       16724    12.0    12.0     6.0
2       16725     9.0     NaN     NaN
3       16726    12.0     NaN    24.0
4       16727    30.0     8.0    10.0
..        ...     ...     ...     ...
145     16868    24.0    12.0     6.0
146     16869     8.0     8.0    12.0
147     16870     5.0    30.0    30.0
148     16871    24.0     NaN    10.0
149     16872     5.0    30.0    10.0

[150 rows x 4 columns]

In [62]:
a=df["Banana"].mean()
df1=df.fillna(a)
df1

Order Id  Apples     Orange     Banana
0       16723     9.0  12.651163   6.000000
1       16724    12.0  12.000000   6.000000
2       16725     9.0  12.651163  12.651163
3       16726    12.0  12.651163  24.000000
4       16727    30.0   8.000000  10.000000
..        ...     ...        ...        ...
145     16868    24.0  12.000000   6.000000
146     16869     8.0   8.000000  12.000000
147     16870     5.0  30.000000  30.000000
148     16871    24.0  12.651163  10.000000
149     16872     5.0  30.000000  10.000000

[150 rows x 4 columns]

In [63]:
import pandas as pd
import numpy as np
a=[[10,20,np.nan],
   [np.nan,30,40],
   [50,60,np.nan]]
cols=["name","age","salary"]
df=pd.DataFrame(a,columns=cols)
a=df["name"].median()
df1=df.fillna(a)
df1

name  age  salary
0  10.0   20    30.0
1  30.0   30    40.0
2  50.0   60    30.0

In [64]:
import pandas as pd
df=pd.read_csv("sales1.csv")
df.head()

Order ID Customer Name                 Product  Quantity
0    166837         Veeru  34in Ultrawide Monitor         2
1    166838         Tarun             Samsung m10         3
2    166839         Kedar            20in Monitor         1
3    166840       Lavanya               iPhone 11         3
4    166841          Venu      Macbook Pro Laptop         2

In [66]:
import pandas as pd
df=pd.read_excel("sales1.xlsx")
df

Order ID Customer Name                 Product  Quantity
0      166837         Veeru  34in Ultrawide Monitor         2
1      166838         Tarun             Samsung m10         3
2      166839         Kedar            20in Monitor         1
3      166840       Lavanya               iPhone 11         3
4      166841          Venu      Macbook Pro Laptop         2
..        ...           ...                     ...       ...
595    167403        Balaji      Macbook Pro Laptop         1
596    167404       Lavanya         ThinkPad Laptop         1
597    167405          Venu           Flatscreen TV         1
598    167406        Siddhu             Samsung m20         2
599    167407         Tarun      LG Washing Machine         1

[600 rows x 4 columns]

In [67]:
import pandas as pd
df=pd.read_table("sales1.tsv")
df

Order ID Customer Name                 Product  Quantity
0      166837         Veeru  34in Ultrawide Monitor         2
1      166838         Tarun             Samsung m10         3
2      166839         Kedar            20in Monitor         1
3      166840       Lavanya               iPhone 11         3
4      166841          Venu      Macbook Pro Laptop         2
..        ...           ...                     ...       ...
595    167403        Balaji      Macbook Pro Laptop         1
596    167404       Lavanya         ThinkPad Laptop         1
597    167405          Venu           Flatscreen TV         1
598    167406        Siddhu             Samsung m20         2
599    167407         Tarun      LG Washing Machine         1

[600 rows x 4 columns]

In [69]:
import pandas as pd
df=pd.read_json("sales1.json")
df

order_id     cust_name                product  quantity
0    16278939       Lavanya        ThinkPad Laptop         2
1    16278966         Kedar          Flatscreen TV         1
2    16278993  Jaya Chandra     Macbook Pro Laptop         2
3    16279020   Mallikarjun              iPhone 11         3
4    16279047        Shahid     LG Washing Machine         1
..        ...           ...                    ...       ...
495  16292304         Sagar               iPhone 7         1
496  16292331    Chaithanya            Samsung m20         1
497  16292358        Siddhu               LG Dryer         2
498  16292385        Siddhu  AA Batteries (4-pack)         1
499  16292412         Sagar              iPhone 11         2

[500 rows x 4 columns]

In [70]:
import numpy as np
a=[10,20,30,40]
b=np.array(a)
print(b)

[10 20 30 40]


In [72]:
import numpy as np
a=[[10,20,30],
   [40,50,60],
   [70,80,90]]
b=np.array(a)
print(b)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [73]:
import numpy as np
a=range(10,20)
b=np.array(a)
print(b)

[10 11 12 13 14 15 16 17 18 19]


In [76]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=np.array(a)
print(b[0])
print(b[1])
print(b[2])

[10 20 30]
[40 50 60]
[70 80 90]


In [79]:
import numpy as np
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[25,35,45],[55,65,75]])
print(a[0,0])
print(a[0,1])
print(a[0,2])

10
20
30


In [82]:
print(b[0,0])
print(b[0,1])
print(b[0,2])

25
35
45


In [84]:
import numpy as np
a=[[10,20,30],[40,50,60]]
b=np.array(a)
print(b.ndim)
print(b.shape)

2
(2, 3)


In [87]:
import numpy as np
a=[[10,20,30],[40,50,60]]
b=np.array(a)
print(b.reshape(2,3))

[[10 20 30]
 [40 50 60]]


In [91]:
import numpy as np
a=[[10,20,0],[30,0,40]]
b=np.array(a)
print(np.count_nonzero(a))

4
